// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBum8GD6WdBAMtU9ODvkhoXHEzmIz_Xphk',
    appId: '1:40959110465:web:56b3359330dbc5b7ce45c0',
    messagingSenderId: '40959110465',
    projectId: 'ecosia-aea5a',
    authDomain: 'ecosia-aea5a.firebaseapp.com',
    storageBucket: 'ecosia-aea5a.appspot.com',
    measurementId: 'G-6XVNGXWB27',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKFYXuwNNVLhb3W6vz9TBu_mSqPWh1kYw',
    appId: '1:40959110465:android:528043e3938581bcce45c0',
    messagingSenderId: '40959110465',
    projectId: 'ecosia-aea5a',
    storageBucket: 'ecosia-aea5a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMSJ8YyOzP6K8olMKBv1E_uQk_xiC0jtc',
    appId: '1:40959110465:ios:1cece6b6eb8339bbce45c0',
    messagingSenderId: '40959110465',
    projectId: 'ecosia-aea5a',
    storageBucket: 'ecosia-aea5a.appspot.com',
    iosClientId: '40959110465-ra4bbucj6h71n9vi5sp7hjsvrtapnish.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecosia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMSJ8YyOzP6K8olMKBv1E_uQk_xiC0jtc',
    appId: '1:40959110465:ios:1cece6b6eb8339bbce45c0',
    messagingSenderId: '40959110465',
    projectId: 'ecosia-aea5a',
    storageBucket: 'ecosia-aea5a.appspot.com',
    iosClientId: '40959110465-ra4bbucj6h71n9vi5sp7hjsvrtapnish.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecosia',
  );
}
